### ISSUE TITLE
Testing this repo

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/drops-8-composer#1]
@greg-1-anderson how should this repo be tested? If a .travis.yml or circle.yml file is added, that could be problematic for anyone forking and using this repo as an upstream.

**Comment by greg-1-anderson** [comment]
Circle supports configuring tests through the web UI without a circle.yml file.

**Comment by greg-1-anderson** [comment]
This repo is obsolete

**Comment by stevector** [comment]
@greg-1-anderson Time to move to https://github.com/pantheon-deprecated ?
